export const DICTIONARY = {
	logIn: "Log in",
	startPlaying: "Start playing!",
	playAsGuest: "Play as Guest!",
	signUp: "Sign up",
	or: "OR",
	password: "Password",
	email: "E-mail",
	cancel: "Cancel",
	username: "Username",
	wrongLoginError: "Username or password is invalid!",
	searchRandom: "Search random",
	playWithFriend: "Play with friend",
	chooseCategory: "Choose Category",
	friendInviteText: "wants to be your friend",
	activeGames: "Active games",
	finishedGames: "Completed games",
	you: "You",
	waitForOpponent: "Wait for opponent",
	play: "Play",
	send: "Send",
	usernameEmailBlankError: "Username and email can not be blank!",
	passwordsError: "Passwords are not the same!",
	rePassword: "Retype password",
	playersUsername: "Player's username",
	monthsNamesShort: [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec",
	],
};
