export const DICTIONARY = {
	logIn: "Log in",
	startPlaying: "Start playing!",
	playAsGuest: "Play as Guest!",
	signIn: "Sign up",
	or: "OR",
	password: "Password",
	email: "E-mail",
	cancel: "Cancel",
	username: "Username",
	wrongLoginError: "Username or password is invalid!",
	searchRandom: "Search random",
	playWithFriend: "Play with friend",
	chooseCategory: "Choose Category",
};
