export const DICTIONARY = {
	logIn: "Zaloguj się",
	startPlaying: "Zacznij grać!",
	playAsGuest: "Zagraj jako gość!",
	signUp: "Zarejestruj się!",
	or: "ALBO",
	password: "Hasło",
	email: "E-mail",
	cancel: "Anuluj",
	username: "Nazwa",
	wrongLoginError: "Nazwa lub hasło jest niepoprawne!",
	searchRandom: "Szukaj losowo",
	playWithFriend: "Zagraj ze znajomym",
	chooseCategory: "Wybierz Kategorie",
	friendInviteText: "chce zostać twoim znajomym!",
	activeGames: "Aktywne gry",
	finishedGames: "Zakończone gry",
	you: "Ty",
	waitForOpponent: "Czekaj na swoja kolej",
	play: "Graj",
	send: "Wyślij",
	usernameEmailBlankError: "Nazwa i email nie mogą być puste!",
	passwordsError: "Podane hasła nie są takie same!",
	rePassword: "Powtórz hasło",
	playersUsername: "Nazwa gracza",
	edit: "Edytuj",
	friends: "Znajomi",
	chooseNewAvatar: "Wybierz nowy avatar",
	newPassword: "Nowe hasło",
	newUsername: "Nowa nazwa",
	usernameTaken: "Nazwa jest już zajęta. Spróbuj inną",
	monthsNamesShort: [
		"Sty",
		"Lut",
		"Mar",
		"Kwi",
		"Maj",
		"Cze",
		"Lip",
		"Sie",
		"Wrz",
		"Paź",
		"Lis",
		"Gru",
	],
};
